# Uncomment the next line to define a global platform for your project
# platform :ios, '14.0'

def shared_pods
  pod 'AEOTPTextField'
  pod 'FloatingTabBarController'
  pod 'RIBs', :git => 'https://github.com/uber/RIBs'
end

target 'RunHSERun' do
  # Comment the next line if you don't want to use dynamic frameworks
  source 'https://github.com/CocoaPods/Specs.git'
  use_frameworks!

  # Pods for RunHSERun
	shared_pods
end

target 'RunHSERunTests' do
	shared_pods
end
