//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: friend_service.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import GRPC
import NIO
import NIOConcurrencyHelpers
import SwiftProtobuf


/// Usage: instantiate `Run_Hse_Run_FriendServiceClient`, then call methods of this protocol to make API calls.
internal protocol Run_Hse_Run_FriendServiceClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: Run_Hse_Run_FriendServiceClientInterceptorFactoryProtocol? { get }

  func addFriend(
    _ request: Run_Hse_Run_AddFriendRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Run_Hse_Run_AddFriendRequest, SwiftProtobuf.Google_Protobuf_Empty>

  func deleteFriend(
    _ request: Run_Hse_Run_DeleteFriendRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Run_Hse_Run_DeleteFriendRequest, SwiftProtobuf.Google_Protobuf_Empty>

  func getFriends(
    _ request: SwiftProtobuf.Google_Protobuf_Empty,
    callOptions: CallOptions?
  ) -> UnaryCall<SwiftProtobuf.Google_Protobuf_Empty, Run_Hse_Run_Users>
}

extension Run_Hse_Run_FriendServiceClientProtocol {
  internal var serviceName: String {
    return "run.hse.run.FriendService"
  }

  /// Unary call to AddFriend
  ///
  /// - Parameters:
  ///   - request: Request to send to AddFriend.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func addFriend(
    _ request: Run_Hse_Run_AddFriendRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Run_Hse_Run_AddFriendRequest, SwiftProtobuf.Google_Protobuf_Empty> {
    return self.makeUnaryCall(
      path: Run_Hse_Run_FriendServiceClientMetadata.Methods.addFriend.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeAddFriendInterceptors() ?? []
    )
  }

  /// Unary call to DeleteFriend
  ///
  /// - Parameters:
  ///   - request: Request to send to DeleteFriend.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func deleteFriend(
    _ request: Run_Hse_Run_DeleteFriendRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Run_Hse_Run_DeleteFriendRequest, SwiftProtobuf.Google_Protobuf_Empty> {
    return self.makeUnaryCall(
      path: Run_Hse_Run_FriendServiceClientMetadata.Methods.deleteFriend.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeDeleteFriendInterceptors() ?? []
    )
  }

  /// Unary call to GetFriends
  ///
  /// - Parameters:
  ///   - request: Request to send to GetFriends.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func getFriends(
    _ request: SwiftProtobuf.Google_Protobuf_Empty,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<SwiftProtobuf.Google_Protobuf_Empty, Run_Hse_Run_Users> {
    return self.makeUnaryCall(
      path: Run_Hse_Run_FriendServiceClientMetadata.Methods.getFriends.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetFriendsInterceptors() ?? []
    )
  }
}

#if compiler(>=5.6)
@available(*, deprecated)
extension Run_Hse_Run_FriendServiceClient: @unchecked Sendable {}
#endif // compiler(>=5.6)

@available(*, deprecated, renamed: "Run_Hse_Run_FriendServiceNIOClient")
internal final class Run_Hse_Run_FriendServiceClient: Run_Hse_Run_FriendServiceClientProtocol {
  private let lock = Lock()
  private var _defaultCallOptions: CallOptions
  private var _interceptors: Run_Hse_Run_FriendServiceClientInterceptorFactoryProtocol?
  internal let channel: GRPCChannel
  internal var defaultCallOptions: CallOptions {
    get { self.lock.withLock { return self._defaultCallOptions } }
    set { self.lock.withLockVoid { self._defaultCallOptions = newValue } }
  }
  internal var interceptors: Run_Hse_Run_FriendServiceClientInterceptorFactoryProtocol? {
    get { self.lock.withLock { return self._interceptors } }
    set { self.lock.withLockVoid { self._interceptors = newValue } }
  }

  /// Creates a client for the run.hse.run.FriendService service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Run_Hse_Run_FriendServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self._defaultCallOptions = defaultCallOptions
    self._interceptors = interceptors
  }
}

internal struct Run_Hse_Run_FriendServiceNIOClient: Run_Hse_Run_FriendServiceClientProtocol {
  internal var channel: GRPCChannel
  internal var defaultCallOptions: CallOptions
  internal var interceptors: Run_Hse_Run_FriendServiceClientInterceptorFactoryProtocol?

  /// Creates a client for the run.hse.run.FriendService service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Run_Hse_Run_FriendServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

#if compiler(>=5.6)
@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
internal protocol Run_Hse_Run_FriendServiceAsyncClientProtocol: GRPCClient {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: Run_Hse_Run_FriendServiceClientInterceptorFactoryProtocol? { get }

  func makeAddFriendCall(
    _ request: Run_Hse_Run_AddFriendRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Run_Hse_Run_AddFriendRequest, SwiftProtobuf.Google_Protobuf_Empty>

  func makeDeleteFriendCall(
    _ request: Run_Hse_Run_DeleteFriendRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Run_Hse_Run_DeleteFriendRequest, SwiftProtobuf.Google_Protobuf_Empty>

  func makeGetFriendsCall(
    _ request: SwiftProtobuf.Google_Protobuf_Empty,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<SwiftProtobuf.Google_Protobuf_Empty, Run_Hse_Run_Users>
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Run_Hse_Run_FriendServiceAsyncClientProtocol {
  internal static var serviceDescriptor: GRPCServiceDescriptor {
    return Run_Hse_Run_FriendServiceClientMetadata.serviceDescriptor
  }

  internal var interceptors: Run_Hse_Run_FriendServiceClientInterceptorFactoryProtocol? {
    return nil
  }

  internal func makeAddFriendCall(
    _ request: Run_Hse_Run_AddFriendRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Run_Hse_Run_AddFriendRequest, SwiftProtobuf.Google_Protobuf_Empty> {
    return self.makeAsyncUnaryCall(
      path: Run_Hse_Run_FriendServiceClientMetadata.Methods.addFriend.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeAddFriendInterceptors() ?? []
    )
  }

  internal func makeDeleteFriendCall(
    _ request: Run_Hse_Run_DeleteFriendRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Run_Hse_Run_DeleteFriendRequest, SwiftProtobuf.Google_Protobuf_Empty> {
    return self.makeAsyncUnaryCall(
      path: Run_Hse_Run_FriendServiceClientMetadata.Methods.deleteFriend.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeDeleteFriendInterceptors() ?? []
    )
  }

  internal func makeGetFriendsCall(
    _ request: SwiftProtobuf.Google_Protobuf_Empty,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<SwiftProtobuf.Google_Protobuf_Empty, Run_Hse_Run_Users> {
    return self.makeAsyncUnaryCall(
      path: Run_Hse_Run_FriendServiceClientMetadata.Methods.getFriends.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetFriendsInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Run_Hse_Run_FriendServiceAsyncClientProtocol {
  internal func addFriend(
    _ request: Run_Hse_Run_AddFriendRequest,
    callOptions: CallOptions? = nil
  ) async throws -> SwiftProtobuf.Google_Protobuf_Empty {
    return try await self.performAsyncUnaryCall(
      path: Run_Hse_Run_FriendServiceClientMetadata.Methods.addFriend.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeAddFriendInterceptors() ?? []
    )
  }

  internal func deleteFriend(
    _ request: Run_Hse_Run_DeleteFriendRequest,
    callOptions: CallOptions? = nil
  ) async throws -> SwiftProtobuf.Google_Protobuf_Empty {
    return try await self.performAsyncUnaryCall(
      path: Run_Hse_Run_FriendServiceClientMetadata.Methods.deleteFriend.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeDeleteFriendInterceptors() ?? []
    )
  }

  internal func getFriends(
    _ request: SwiftProtobuf.Google_Protobuf_Empty,
    callOptions: CallOptions? = nil
  ) async throws -> Run_Hse_Run_Users {
    return try await self.performAsyncUnaryCall(
      path: Run_Hse_Run_FriendServiceClientMetadata.Methods.getFriends.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetFriendsInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
internal struct Run_Hse_Run_FriendServiceAsyncClient: Run_Hse_Run_FriendServiceAsyncClientProtocol {
  internal var channel: GRPCChannel
  internal var defaultCallOptions: CallOptions
  internal var interceptors: Run_Hse_Run_FriendServiceClientInterceptorFactoryProtocol?

  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Run_Hse_Run_FriendServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

#endif // compiler(>=5.6)

internal protocol Run_Hse_Run_FriendServiceClientInterceptorFactoryProtocol: GRPCSendable {

  /// - Returns: Interceptors to use when invoking 'addFriend'.
  func makeAddFriendInterceptors() -> [ClientInterceptor<Run_Hse_Run_AddFriendRequest, SwiftProtobuf.Google_Protobuf_Empty>]

  /// - Returns: Interceptors to use when invoking 'deleteFriend'.
  func makeDeleteFriendInterceptors() -> [ClientInterceptor<Run_Hse_Run_DeleteFriendRequest, SwiftProtobuf.Google_Protobuf_Empty>]

  /// - Returns: Interceptors to use when invoking 'getFriends'.
  func makeGetFriendsInterceptors() -> [ClientInterceptor<SwiftProtobuf.Google_Protobuf_Empty, Run_Hse_Run_Users>]
}

internal enum Run_Hse_Run_FriendServiceClientMetadata {
  internal static let serviceDescriptor = GRPCServiceDescriptor(
    name: "FriendService",
    fullName: "run.hse.run.FriendService",
    methods: [
      Run_Hse_Run_FriendServiceClientMetadata.Methods.addFriend,
      Run_Hse_Run_FriendServiceClientMetadata.Methods.deleteFriend,
      Run_Hse_Run_FriendServiceClientMetadata.Methods.getFriends,
    ]
  )

  internal enum Methods {
    internal static let addFriend = GRPCMethodDescriptor(
      name: "AddFriend",
      path: "/run.hse.run.FriendService/AddFriend",
      type: GRPCCallType.unary
    )

    internal static let deleteFriend = GRPCMethodDescriptor(
      name: "DeleteFriend",
      path: "/run.hse.run.FriendService/DeleteFriend",
      type: GRPCCallType.unary
    )

    internal static let getFriends = GRPCMethodDescriptor(
      name: "GetFriends",
      path: "/run.hse.run.FriendService/GetFriends",
      type: GRPCCallType.unary
    )
  }
}

/// To build a server, implement a class that conforms to this protocol.
internal protocol Run_Hse_Run_FriendServiceProvider: CallHandlerProvider {
  var interceptors: Run_Hse_Run_FriendServiceServerInterceptorFactoryProtocol? { get }

  func addFriend(request: Run_Hse_Run_AddFriendRequest, context: StatusOnlyCallContext) -> EventLoopFuture<SwiftProtobuf.Google_Protobuf_Empty>

  func deleteFriend(request: Run_Hse_Run_DeleteFriendRequest, context: StatusOnlyCallContext) -> EventLoopFuture<SwiftProtobuf.Google_Protobuf_Empty>

  func getFriends(request: SwiftProtobuf.Google_Protobuf_Empty, context: StatusOnlyCallContext) -> EventLoopFuture<Run_Hse_Run_Users>
}

extension Run_Hse_Run_FriendServiceProvider {
  internal var serviceName: Substring {
    return Run_Hse_Run_FriendServiceServerMetadata.serviceDescriptor.fullName[...]
  }

  /// Determines, calls and returns the appropriate request handler, depending on the request's method.
  /// Returns nil for methods not handled by this service.
  internal func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "AddFriend":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Run_Hse_Run_AddFriendRequest>(),
        responseSerializer: ProtobufSerializer<SwiftProtobuf.Google_Protobuf_Empty>(),
        interceptors: self.interceptors?.makeAddFriendInterceptors() ?? [],
        userFunction: self.addFriend(request:context:)
      )

    case "DeleteFriend":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Run_Hse_Run_DeleteFriendRequest>(),
        responseSerializer: ProtobufSerializer<SwiftProtobuf.Google_Protobuf_Empty>(),
        interceptors: self.interceptors?.makeDeleteFriendInterceptors() ?? [],
        userFunction: self.deleteFriend(request:context:)
      )

    case "GetFriends":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<SwiftProtobuf.Google_Protobuf_Empty>(),
        responseSerializer: ProtobufSerializer<Run_Hse_Run_Users>(),
        interceptors: self.interceptors?.makeGetFriendsInterceptors() ?? [],
        userFunction: self.getFriends(request:context:)
      )

    default:
      return nil
    }
  }
}

#if compiler(>=5.6)

/// To implement a server, implement an object which conforms to this protocol.
@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
internal protocol Run_Hse_Run_FriendServiceAsyncProvider: CallHandlerProvider {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: Run_Hse_Run_FriendServiceServerInterceptorFactoryProtocol? { get }

  @Sendable func addFriend(
    request: Run_Hse_Run_AddFriendRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> SwiftProtobuf.Google_Protobuf_Empty

  @Sendable func deleteFriend(
    request: Run_Hse_Run_DeleteFriendRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> SwiftProtobuf.Google_Protobuf_Empty

  @Sendable func getFriends(
    request: SwiftProtobuf.Google_Protobuf_Empty,
    context: GRPCAsyncServerCallContext
  ) async throws -> Run_Hse_Run_Users
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Run_Hse_Run_FriendServiceAsyncProvider {
  internal static var serviceDescriptor: GRPCServiceDescriptor {
    return Run_Hse_Run_FriendServiceServerMetadata.serviceDescriptor
  }

  internal var serviceName: Substring {
    return Run_Hse_Run_FriendServiceServerMetadata.serviceDescriptor.fullName[...]
  }

  internal var interceptors: Run_Hse_Run_FriendServiceServerInterceptorFactoryProtocol? {
    return nil
  }

  internal func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "AddFriend":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Run_Hse_Run_AddFriendRequest>(),
        responseSerializer: ProtobufSerializer<SwiftProtobuf.Google_Protobuf_Empty>(),
        interceptors: self.interceptors?.makeAddFriendInterceptors() ?? [],
        wrapping: self.addFriend(request:context:)
      )

    case "DeleteFriend":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Run_Hse_Run_DeleteFriendRequest>(),
        responseSerializer: ProtobufSerializer<SwiftProtobuf.Google_Protobuf_Empty>(),
        interceptors: self.interceptors?.makeDeleteFriendInterceptors() ?? [],
        wrapping: self.deleteFriend(request:context:)
      )

    case "GetFriends":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<SwiftProtobuf.Google_Protobuf_Empty>(),
        responseSerializer: ProtobufSerializer<Run_Hse_Run_Users>(),
        interceptors: self.interceptors?.makeGetFriendsInterceptors() ?? [],
        wrapping: self.getFriends(request:context:)
      )

    default:
      return nil
    }
  }
}

#endif // compiler(>=5.6)

internal protocol Run_Hse_Run_FriendServiceServerInterceptorFactoryProtocol {

  /// - Returns: Interceptors to use when handling 'addFriend'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeAddFriendInterceptors() -> [ServerInterceptor<Run_Hse_Run_AddFriendRequest, SwiftProtobuf.Google_Protobuf_Empty>]

  /// - Returns: Interceptors to use when handling 'deleteFriend'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeDeleteFriendInterceptors() -> [ServerInterceptor<Run_Hse_Run_DeleteFriendRequest, SwiftProtobuf.Google_Protobuf_Empty>]

  /// - Returns: Interceptors to use when handling 'getFriends'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeGetFriendsInterceptors() -> [ServerInterceptor<SwiftProtobuf.Google_Protobuf_Empty, Run_Hse_Run_Users>]
}

internal enum Run_Hse_Run_FriendServiceServerMetadata {
  internal static let serviceDescriptor = GRPCServiceDescriptor(
    name: "FriendService",
    fullName: "run.hse.run.FriendService",
    methods: [
      Run_Hse_Run_FriendServiceServerMetadata.Methods.addFriend,
      Run_Hse_Run_FriendServiceServerMetadata.Methods.deleteFriend,
      Run_Hse_Run_FriendServiceServerMetadata.Methods.getFriends,
    ]
  )

  internal enum Methods {
    internal static let addFriend = GRPCMethodDescriptor(
      name: "AddFriend",
      path: "/run.hse.run.FriendService/AddFriend",
      type: GRPCCallType.unary
    )

    internal static let deleteFriend = GRPCMethodDescriptor(
      name: "DeleteFriend",
      path: "/run.hse.run.FriendService/DeleteFriend",
      type: GRPCCallType.unary
    )

    internal static let getFriends = GRPCMethodDescriptor(
      name: "GetFriends",
      path: "/run.hse.run.FriendService/GetFriends",
      type: GRPCCallType.unary
    )
  }
}
